version: "3.5"

services:
  api01: &api
    image: ghcr.io/vinisoaresr/backend-rinha:latest
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=3000
    ports:
      - "9999:3000"
    depends_on:
      db:
        condition: service_healthy
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.45"
    #       memory: "200MB"

  # api02:
  #   <<: *api
  #   hostname: api02
  #   environment:
  #     - DB_HOSTNAME=db
  #     - PORT=3000
  #   ports:
  #     - "3002:3000"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.15"
  #         memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    # volumes:
    # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -p 5432 -c checkpoint_timeout=600 -c max_wal_size=4096
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.45"
    #       memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
