name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: 2.3.0
  postgres: 3.0.8
  shelf: 1.4.0
  shelf_router: 1.1.0

dev_dependencies:
  http: 0.13.0
  lints: 2.0.0
  test: 1.21.0
  test_process: 2.1.0

executables:
  main: server